name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Triggers only when a version tag (e.g., v1.0.0) is pushed

permissions:
  contents: read  # Read access to repository
  id-token: write  # Required for PyPI Trusted Publishing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/kaleidoscope-sdk/  # Update with your package name

    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
